services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - 8081:8081
  public:
    build: ./public
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - api